### ISSUE TITLE
Application suggestions

### ISSUE THREAD

**Issue by bittin** [bittin/iso-build#1]
I have been testing the image and it works really well so far. I added and removed some components that are more in keeping with the workflow of the WM

xscreensaver
lxsession
pcmanfm-qt (replaces thunar)
alacritty (replaces shipped terminal)
luakit
howl (replaces mousepad)
libvoikko (luakit dep)
nuspell (luakit dep)
hunspell(en_us for my system, luakit dep)
xcursor-maia (replaces xcursor-breeze which removes manjaro-awesome-settings)
manjaro-settings-manager

The shipped config also defines pa-applet as the volume control, but I feel pasystray is more flexible.

**Comment by bittin** [comment]
@zeroability had time to check on your change requests now and building a new image now with Maia
not sure if i want to replace the other software as i think the ones picked now are good not sure about adding xscreensaver i barely use screensavers myself but https://tools.suckless.org/slock/ so might include that, any feedback from others?

**Comment by ZeroAbility** [comment]
Here are two more, but they are not in the repos:

https://github.com/lite-xl/lite-xl
https://github.com/endaaman/tym

**Comment by bittin** [comment]
> Here are two more, but they are not in the repos:
> 
> https://github.com/lite-xl/lite-xl https://github.com/endaaman/tym

can't be added as they are not in the repos

**Comment by bittin** [comment]
Closing this issue as its old and i have changed some summer 2021

feel free to send a PR too: https://github.com/bittin/iso-profiles-1/blob/master/community/awesome/Packages-Desktop 
if you want other software exchanged or added / removed in the future
