### ISSUE TITLE
How to download full iso (not minimal)

### ISSUE THREAD

**Issue by tsingwang** [bittin/iso-build#10]
I know manjaro not provide manjaro-awesome edition now. Thank you for your work.
But I have two question.
1. Is it possible to get the community to adopt this version?
2. Why is there no full version of the latest release?

**Comment by bittin** [comment]
@boredland Hey could you help me with this: https://github.com/bittin/iso-build/issues/10 ? the configuration says it should build full ISOs too, but only builds minimal ISOs for some reason

**Comment by boredland** [comment]
not sure, but have you figured out what those errors mean?

![image](https://user-images.githubusercontent.com/4662748/184241098-01094146-9f6c-4203-9c92-e396bd81a750.png)

**Comment by bittin** [comment]
> not sure, but have you figured out what those errors mean?
> 
> ![image](https://user-images.githubusercontent.com/4662748/184241098-01094146-9f6c-4203-9c92-e396bd81a750.png)

nope

**Comment by boredland** [comment]
I think this may be some kind of race condition (but not 100% sure) where the release is removed due to a failing job, so the uploads fail.

**Comment by boredland** [comment]
also there seems to be an issue with you trying to install the base-devel group, which leads to a user-input prompt: 
![image](https://user-images.githubusercontent.com/4662748/184295009-4a8c491b-abfc-434f-8d54-5aed0f89c90c.png)

**Comment by bittin** [comment]
now it will all broke, sick with cold and migrane however, will try to resolve this when i have more energy

**Comment by bittin** [comment]
doing another test atm

**Comment by bittin** [comment]
This now works, full isos building for: https://github.com/bittin/iso-build/releases/tag/202208130959 at the moment

thanks @boredland for help with troubleshooting and @tsingwang for reporting this 
(sorry it took over 1,5 month to fix i am pretty busy and don't give this enough love as i should)
