### ISSUE TITLE
no audio, many issues

### ISSUE THREAD

**Issue by StarAssassin64** [bittin/iso-build#12]
idrk if it is me, or what, but after installing, i have no audio. i tried downloading pulseaudio and it still doesnt want to work. maybe once this gets fixed, ill move back over because im loving the awesome wm and i wish i could easily install it on the plasma official release of manjaro.

**Comment by bittin** [comment]
Hey!

Sorry for late reply, has had too much to do but audio works for me with the https://github.com/bittin/iso-build/releases/download/202208101222/manjaro-awesome-21.3.2-minimal-220810-linux519.iso ISO i built today 

is this still a problem for you?

**Comment by StarAssassin64** [comment]
Yeah, it was. I couldn't figure out how to fix it so I just reinstalled Manjaro KDE Plasma. I might be able to figure it out now because I had to for a base arch install. Is there any audio managers installed, like alsa?

**Comment by bittin** [comment]
nope, but pavucontrol and alsamixer can easily be installed with sudo pacman -S pavucontrol alsa-utils 

Closing this as fixed as audio works
