### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by leosuncin** [bittin/iso-build#16]
There are no new releases since [2022-10-05](https://github.com/bittin/iso-build/releases/tag/202210051727)

Is this still active?

**Comment by bittin** [comment]
I think the Github Actions is broken and i don't have skills enough to fix them and don't really use this distro myself anymore maybe @boredland can look at it if he has time 

If not it would be great with someone that takes this project of my hands as i don't feel i have the time and energy enough for it

**Comment by boredland** [comment]
You need to merge upstream iso profiles to [your](https://github.com/bittin/iso-profiles-1) iso-profiles, because some tools got deprecated (namely: manjaro-firmware).

**Comment by bittin** [comment]
> You need to merge upstream iso profiles to [your](https://github.com/bittin/iso-profiles-1) iso-profiles, because some tools got deprecated (namely: manjaro-firmware).


Alright feel like sending a PR or telling me where to find that file?

**Comment by boredland** [comment]
[here](https://github.com/bittin/iso-profiles-1/blob/master/shared/Packages-Root#L51).

**Comment by bittin** [comment]
alright if that was it there should be new builds in some hour lets hope

**Comment by bittin** [comment]
@leosuncin https://github.com/bittin/iso-build/releases/tag/202303121429 there is a new build here now 
sorry it took 4,5 months i don't really give this thing as much work as it deserves so if someone else wants to take over feel free otherwise its gonna be very sporadic

**Comment by bittin** [comment]
Updated and working builds is now up again after some months of not having any at all
